# Generated by Django 4.0 on 2022-01-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_owner_room_id_alter_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=6),
        ),
    ]
