# Generated by Django 4.0 on 2022-01-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('room', '0004_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedrooms',
            name='buyer_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=6, null=True),
        ),
    ]
