# Generated by Django 4.0 on 2022-01-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='contact_deatils',
            new_name='contact_details',
        ),
    ]
