# Generated by Django 4.0 on 2022-01-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_rename_contact_deatils_room_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
